communication_config:
  eta1: 12.8
  eta2: 0.11
  eta_LoS: 1.6
  eta_NLoS: 23
  fc: 2e9 #  2GHz or 2e9 hz carrier frequency
  eta3: 1.68 #n --<Path Loss Modeling for Vehicle-to-Vehicle Communications>
  eta4: 1.7 #<Path Loss Modeling for Vehicle-to-Vehicle Communications>
  d0: 10 # d0 --<Path Loss Modeling for Vehicle-to-Vehicle Communications>
  Lcvv: 1.5 # PLc --<Path Loss Modeling for Vehicle-to-Vehicle Communications>
  L0vv: 85.0 # PL0 --<Path Loss Modeling for Vehicle-to-Vehicle Communications>
  p_noise: 1e-12 #noise_power=noise_power_spectral_density*bandwidth, U2I is 1e-11 U2U is 1e-15

vehicle_path_config:
  vehicle_num: 10
  run_time: 8000
  car_speed: 0.8
  time_slot: 0.2
  path_num: 10
  forward_probability: 0.3

uav_config:
  pos:
    - [-250, 100, -250]
    - [-250, 100, 250]
    - [250, 100, -250]
    - [250, 100, 250]

  bandwidth: 1e6        # Hz or 1MHz
  E_n: 7e-8           # J/cycle--the CPU energy consumption to implement one cycle at node ut
  P_n: 1              # w--the transmit power of node ut
  type: "uav"
  w: 8               # cycle/bit--the number of CPU cycles required to compute one bit (from gpt suggest)
  C_n: 3e7            # cycle/s --the available computation resource, i.e., in cycle/s, of node
  #communication_range: 36 #m--communication radius is 36 m

vehicle_config:
  bandwidth: 2e6      # Hz or 2 MHz,<A Multihop Task Offloading Decision Model in MEC-Enabled Internet of Vehicles> is 10 MHZ
  E_n: [9e-8, 11e-8, 13e-8, 15e-8, 17e-8, 19e-8, 21e-8, 22e-8, 23e-8, 24e-8] # J/cycle--the CPU energy consumption to implement one cycle at node ut
  P_n: [1.58,1.59,2.0] # w--the transmit power of node ut,<A Multihop Task Offloading Decision Model in MEC-Enabled Internet of Vehicles> is 32 dBm is approximately equal to 1.58 w
  type: "vehicle"
  w: 8               # cycle/bit--the number of CPU cycles required to compute one bit (from gpt suggest)
  C_n: [4.5e7, 9e7, 13.5e7, 18e7, 22.5e7, 27e7, 31.5e7, 36e7, 40.5e7, 45e7]  # cycle/s --the available computation resource, i.e., in cycle/s, of node

  vehicle_communication_range: 200 # m




e_weight: 1
t_weight: 20

data_size: 1e8 #bits
task_dimensions: 50
task_split_granularity: [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1]

random_seed: 1

max_loss: 120
min_loss: 80

